create table Game_Instance(
	lvl float(6,2) NOT NULL,
	towers_killed float(6,2) NOT NULL,
	creep_score float(6,2) NOT NULL,
	kills float(6,2) NOT NULL,
	assists float(6,2) NOT NULL,
	game_time time NOT NULL,
	barons float(6,2) NOT NULL,
	dragons float(6,2) NOT NULL,
	PRIMARY KEY (lvl,towers_killed,creep_score,kills,assists,game_time,barons,dragons)
);

create table Champs_Stats(
	champ_id varchar(10) NOT NULL,
	health float(6,2),
	health_regen numeric(3,2),
	mana float(6,2),
	mana_regen numeric(3,2),
	armor float(6,2),
	magic_resist float(6,2),
	attack_damage float(6,2),
	ability_power float(6,2),
	flat_armor_pen float(6,2),
	percent_amror_pen float(6,2),
	flat_magic_pen float(6,2),
	percent_magic_pen float(6,2),
	attack_speed float(6,2),
	flat_move_speed float(6,2),
	percent_move_speed float(6,2),
	crit_chance float(6,2),
	cooldown_reduction float(6,2),
	lifesteal float(6,2),
	spellvamp float(6,2),
	PRIMARY KEY (champ_id)
);

create table Item_Stats(
    item_id varchar(10) NOT NULL,
    gold_value float(6,2),
    health float(6,2),
	health_regen numeric(3,2),
	mana float(6,2),
	mana_regen numeric(3,2),
	armor float(6,2),
	magic_resist float(6,2),
	attack_damage float(6,2),
	ability_power float(6,2),
	flat_armor_pen float(6,2),
	percent_amror_pen float(6,2),
	flat_magic_pen float(6,2),
	percent_magic_pen float(6,2),
	attack_speed float(6,2),
	flat_move_speed float(6,2),
	percent_move_speed float(6,2),
	crit_chance float(6,2),
	cooldown_reduction float(6,2),
	lifesteal float(6,2),
	spellvamp float(6,2),
	PRIMARY KEY (item_id)
);

create table Rune_Page_Stats(
    rune_id varchar(30) NOT NULL,
    quantity float(6,2),
    ability_power float(6,2),
    armor float(6,2),
    armor_pen float(6,2),
    magic_resist float(6,2),
    magic_pen float(6,2),
    attack_damage float(6,2),
    attack_speed float(6,2),
    cooldown_reduction float(6,2),
    crit_chance float(6,2),
   	crit_damage float(6,2),
   	energy float(6,2),
   	energy_regen numeric(3,2),
   	health float(6,2),
   	health_regen numeric(3,2),
    percent_health float(6,2),
    mana float(6,2),
    mana_regen numeric(3,2),
    lifesteal float(6,2),
    move_speed float(6,2),
    PRIMARY KEY (rune_id)
);

create table Dragon_Buff_Stats(
    dragon_num float(6,2) NOT NULL,
    bonus_attack_damage float(6,2),
    bonus_ability_power float(6,2),
    bonus_movement_speed float(6,2),
    PRIMARY KEY (dragon_num)
);

create table Current_Stats(
	gold float(6,2),
    health float(6,2),
	health_regen numeric(3,2),
	mana float(6,2),
	mana_regen numeric(3,2),
	armor float(6,2),
	magic_resist float(6,2),
	attack_damage float(6,2),
	ability_power float(6,2),
	flat_armor_pen float(6,2),
	percent_armor_pen float(6,2),
	flat_magic_pen float(6,2),
	percent_magic_pen float(6,2),
	attack_speed float(6,2),
	flat_move_speed float(6,2),
	percent_move_speed float(6,2),
	crit_chance float(6,2),
	crit_damage float(6,2),
	energy float(6,2),
	energy_regen float(6,2),
	cooldown_reduction float(6,2),
	lifesteal float(6,2),
	spellvamp float(6,2),
	attackrange float(6,2),
	lvl float(6,2) NOT NULL,
	towers_killed float(6,2) NOT NULL,
	creep_score float(6,2) NOT NULL,
	kills float(6,2) NOT NULL,
	assists float(6,2) NOT NULL,
	game_time time NOT NULL,
	barons float(6,2) NOT NULL,
	dragons float(6,2) NOT NULL,
	PRIMARY KEY (lvl,towers_killed,creep_score,kills,assists,game_time,barons,dragons)
);